env: "local"
storage:
  path: "sql/storage.db"
  migrations: "sql/migrations"
http_server:
  address: "localhost:8080"
  timeout: 4s
  idle_timeout: 30s
bot_token: "7976373927:AAE5Xv7GnBnuC5FtvlQ5TlLn6O_yWIMZmk0"
